
import random
a = int(input('Enter the lower bound: '))
b = int(input('Enter the upper bound: '))

randomNumber = random.randint(a, b)
print('Random number generated by python: ',randomNumber)
print('You have 7 chances to guess the random number chosen by the software.')
chances = 7
while chances >= 1:
    numberGuessed = int(input('Guess the number'))
    if numberGuessed == randomNumber:
        print('Your guessed right! ')
        quit()
    elif numberGuessed < randomNumber:
        print('You guessed too small!')
    else:
        print('You guessed too big!')
    chances = chances - 1
if(chances == 0):
    print('Sorry! you have no more chances left')